### ISSUE TITLE
Brightness after idle.

### ISSUE THREAD

**Issue by Martin1134** [markusressel/keyboard-backlight-daemon#37]
Is there a way to set the brightness after the keyboard backlight turns on after idle? 

Because now, every time it lights up again, it goes to full brightness. 

Before idle, after idle

![Bildschirmfoto vom 2023-04-23 12-28-29](https://user-images.githubusercontent.com/44879342/233834480-fd277499-f3ac-486a-b270-723f6f82cfaf.png)

**Comment by markusressel** [comment]
Hey @Martin1134 ! :heart: 

I am not sure what your intention is. :thinking:   
kbd tries to memorize the brightness that was set by the user when the "idle" state is detected, and restores that when the state goes back to "active". There is (currently) no way to force the target brightness to a specific level through kbd, if thats what you are after.

**Comment by markusressel** [comment]
Feel free to share the link to the project you found, maybe it can help others as well :smile:

**Comment by Martin1134** [comment]
Sure, there it is: https://github.com/VorpalBlade/keyboard-backlightd

:)
